"""
Arguments for testlink endpoints
"""
PROJECT_ID = 'testprojectid'
DEVKEY = 'devKey'
PLAN_ID = 'testplanid'
BUILD_ID = 'buildid'
TESTCASE_ID = 'testcaseid'
KEYWORD_ID = 'keywordid'
KEYWORDS = 'keywords'
EXECUTED = 'executed'
ASSIGNED_TO = 'assignedto'
STATUS = 'status'
EXECUTION_TYPE = 'executiontype'
GET_STEP_INFO = 'getstepinfo'
EXTERNAL_ID = 'testcaseexternalid'
SUITE_ID = 'testsuiteid'
VERSION = 'version'
BUILD_NAME = 'buildname'
NOTES = 'notes'
GUESS = 'guess'
BUG_ID = 'bugid'
PLATFORM_ID = 'platformid'
PLATFORM_NAME = 'platformname'
CUSTOM_FIELDS = 'customfields'
OVERWRITE = 'overwrite'
TESTCASE_NAME = 'testcasename'
TESTSUITE_NAME = 'testsuitename'
AUTHOR = 'authorlogin'
SUMMARY = 'summary'
EXECUTION_ID = 'executionid'
DETAILS = 'details'
PARENT_ID = 'parentid'
ORDER = 'order'
CHECK_DUPLICATE_NAME = 'checkduplicatedname'
ACTION_ON_DUPLICATED_NAME = 'actiononduplicatedname'
PREFIX = 'testcaseprefix'
PROJECT_NAME = 'testprojectname'
PLAN_NAME = 'testplanname'
ACTIVE = 'active'
PUBLIC = 'public'
BUILD_NAME = 'buildname'
BUILD_NOTES = 'buildnotes'


STEPS = 'steps'
STEP_NUMBER = 'step_number'
ACTIONS = 'actions'
EXPECTED_RESULTS = 'expected_results'
STEP_EXECUTION_TYPE = 'execution_type'
EXECUTION_TYPE = 'executiontype'


#PLAN_ID_LATEST = 'tplanid'
"""
	public static $devKeyParamName = "devKey";
	public static $testCaseIDParamName = "testcaseid";
	public static $testCaseExternalIDParamName = "testcaseexternalid";
	public static $testPlanIDParamName = "testplanid";
	public static $testProjectIDParamName = "testprojectid";
	public static $testSuiteIDParamName = "testsuiteid";
	public static $statusParamName = "status";
	public static $buildIDParamName = "buildid";
	public static $noteParamName = "notes";
	public static $timeStampParamName = "timestamp";
	public static $guessParamName = "guess";
	public static $deepParamName = "deep";
	public static $testModeParamName = "testmode";
	public static $buildNameParamName = "buildname";
	public static $buildNotesParamName = "buildnotes";
	public static $automatedParamName = "automated";
	public static $testCaseNameParamName = "testcasename";
	public static $keywordIDParamName = "keywordid";
	public static $executedParamName = "executed";
	public static $assignedToParamName = "assignedto";
	public static $executeStatusParamName = "executestatus";
	public static $testSuiteNameParamName = "testsuitename";
	public static $testProjectNameParamName = "testprojectname";
	public static $testCasePrefixParamName = "testcaseprefix";
	public static $customFieldNameParamName = "customfieldname";
	public static $summaryParamName = "summary";
	public static $stepsParamName = "steps";
    public static $expectedResultsParamName = "expectedresults";
    public static $authorLoginParamName = "authorlogin";
    public static $executionTypeParamName = "executiontype";
    public static $importanceParamName = "importance";
    public static $orderParamName = "order";
    public static $internalIDParamName = "internalid";
    public static $checkDuplicatedNameParamName = "checkduplicatedname";
    public static $actionOnDuplicatedNameParamName = "actiononduplicatedname";
    public static $keywordNameParamName = "keywords";
    public static $versionNumberParamName = "version";
    public static $executionOrderParamName = "executionorder";
    public static $urgencyParamName = "urgency";
    public static $requirementsParamName = "requirements";
    public static $detailsParamName = "details";
	public static $bugIDParamName = "bugid";		
	public static $parentIDParamName = "parentid";		
	public static $testPlanNameParamName = "testplanname";
	public static $activeParamName = "active";
    public static $publicParamName = "public";
    public static $nodeIDParamName = "nodeid";
    public static $customFieldsParamName = "customfields";
    public static $executionIDParamName = "executionid";
    public static $preconditionsParamName = "preconditions";
    public static $platformNameParamName = "platformname";
    public static $platformIDParamName = "platformid";
	public static $overwriteParamName = "overwrite";
	public static $testCasePathNameParamName = "testcasepathname";
    public static $userParamName = "user";
    public static $getStepsInfoParamName = "getstepsinfo";
    """
